import { SkillItem, Project, RecruiterReason } from './types';

export const PERSONAL_INFO = {
  name: 'Edivho Febrian Putra',
  role: 'Software Developer & Information Systems Student',
  roleid: 'Software Developer & Mahasiswa Sistem Informasi',
  university: 'Universitas Bakrie',
  location: 'Jakarta, Indonesia',
  email: 'edivho01@gmail.com',
  github: 'https://github.com', // Placeholder or standard profile
  linkedin: 'https://linkedin.com',
  bioEn: 'I am an Information Systems student at Universitas Bakrie with a strong passion for software development, web technologies, and digital product innovation. I enjoy building scalable applications, designing user-friendly interfaces, and solving business problems through technology. My experience spans full-stack web development, database management, UI/UX design, and project leadership through organizational and software development activities.',
  bioId: 'Saya adalah mahasiswa Sistem Informasi di Universitas Bakrie dengan ketertarikan mendalam dalam pengembangan perangkat lunak, teknologi web, dan inovasi produk digital. Saya senang membangun aplikasi yang skalabel, merancang antarmuka pengguna yang ramah, serta memecahkan masalah bisnis melalui teknologi. Pengalaman saya mencakup pengembangan web full-stack, manajemen basis data, desain UI/UX, dan kepemimpinan proyek melalui aktivitas organisasi serta pengembangan peranti lunak.',
  avatar: '/src/assets/images/edivho_badge_photo_1781964134515.png',
};

export const BRAND_HEADLINES = [
  {
    id: 'h1',
    textEn: 'Software Developer. Problem Solver. Digital Product Builder.',
    textId: 'Software Developer. Pemecah Masalah. Pembangun Produk Digital.',
  },
  {
    id: 'h2',
    textEn: 'Transforming Ideas Into Modern Digital Solutions.',
    textId: 'Mengubah Ide Menjadi Solusi Digital Modern.',
  },
  {
    id: 'h3',
    textEn: 'Designing Experiences. Developing Solutions. Creating Impact.',
    textId: 'Merancang Pengalaman. Mengembangkan Solusi. Menciptakan Dampak.',
  },
];

export const SKILL_ITEMS: SkillItem[] = [
  // Frontend
  {
    id: 'html5',
    name: 'HTML5',
    level: 'Advanced',
    percentage: 90,
    category: 'frontend',
    description: 'Sintaksis markah modern, struktur semantik, ramah SEO, dan aksesibilitas web.',
    isStarred: true,
  },
  {
    id: 'css3',
    name: 'CSS3',
    level: 'Advanced',
    percentage: 85,
    category: 'frontend',
    description: 'Tata letak Flexbox/Grid, animasi tingkat lanjut, responsive layout, dan kustom variabel.',
  },
  {
    id: 'js',
    name: 'JavaScript (ES6+)',
    level: 'Advanced',
    percentage: 88,
    category: 'frontend',
    description: 'Asynchronous programming, event loop, DOM manipulation, manipulasi array modern, dan fungsional programing.',
    isStarred: true,
  },
  {
    id: 'react',
    name: 'React.js',
    level: 'Advanced',
    percentage: 86,
    category: 'frontend',
    description: 'Siklus hidup komponen, custom Hooks, manajemen state, optimasi render, dan ekosistem SPA modern.',
    isStarred: true,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    level: 'Advanced',
    percentage: 82,
    category: 'frontend',
    description: 'Sistem tipe statis, generics, interfaces, strict mode, serta integrasi aman dengan bundler modern.',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    level: 'Advanced',
    percentage: 88,
    category: 'frontend',
    description: 'Utility-first styling, arsitektur tema, kustomisasi token, responsive design terintegrasi, dan performa tinggi.',
  },

  // Backend & Database
  {
    id: 'supabase',
    name: 'Supabase',
    level: 'Intermediate',
    percentage: 78,
    category: 'backend',
    description: 'PostgreSQL as a Service, autentikasi user, kebijakan keamanan baris (RLS), real-time database, dan API auto-generated.',
    isStarred: true,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    level: 'Intermediate',
    percentage: 80,
    category: 'backend',
    description: 'Desain skema basis data relasional, pengindeksan, optimasi query, normalisasi data, dan relasi tabel.',
    isStarred: true,
  },
  {
    id: 'xampp',
    name: 'XAMPP',
    level: 'Intermediate',
    percentage: 75,
    category: 'backend',
    description: 'Pengelolaan lingkungan server lokal (Apache, MySQL, PHP) untuk pengujian aplikasi mandiri.',
  },
  {
    id: 'rest_api',
    name: 'REST API Integration',
    level: 'Advanced',
    percentage: 84,
    category: 'backend',
    description: 'Desain endpoint RESTful, otentikasi Bearer/JWT, pengelolaan request/response asinkronus, serta penanganan error.',
  },

  // Mobile
  {
    id: 'dart',
    name: 'Dart',
    level: 'Intermediate',
    percentage: 72,
    category: 'mobile',
    description: 'Pemrograman berbasis objek berorientasi tipe tangguh yang menggerakkan logika aplikasi mobile.',
    isStarred: true,
  },
  {
    id: 'flutter',
    name: 'Flutter',
    level: 'Intermediate',
    percentage: 74,
    category: 'mobile',
    description: 'Pengembangan aplikasi multiplatform (Android/iOS) dengan performa native melalui satu basis kode deklaratif.',
    isStarred: true,
  },

  // Tools & Productivity
  {
    id: 'git',
    name: 'Git & GitHub',
    level: 'Advanced',
    percentage: 85,
    category: 'tools',
    description: 'Kontrol versi terdistribusi, manajemen branch, pull requests, kolaborasi kode, dan setup repositori.',
  },
  {
    id: 'vscode',
    name: 'VS Code',
    level: 'Advanced',
    percentage: 90,
    category: 'tools',
    description: 'Optimalisasi editor, integrasi extensions pengembang, debugging terintegrasi, dan manajemen workspace.',
  },
  {
    id: 'figma',
    name: 'Figma',
    level: 'Intermediate',
    percentage: 78,
    category: 'tools',
    description: 'Merancang wireframe, maket visual berdefinisi tinggi, komponen interaktif, dan prototyping UI/UX.',
  },
  {
    id: 'canva',
    name: 'Canva',
    level: 'Advanced',
    percentage: 85,
    category: 'tools',
    description: 'Pembuatan material presentasi komunikatif, infografis, dan aset visual pendukung produk digital.',
  },
  {
    id: 'msoffice',
    name: 'Microsoft Office',
    level: 'Advanced',
    percentage: 88,
    category: 'tools',
    description: 'Analisis data kuantitatif menggunakan Excel, penyusunan laporan akademis formal, dan dokumentasi bisnis.',
  },

  // Software Engineering Concepts
  {
    id: 'ui_ux',
    name: 'UI/UX Design',
    level: 'Intermediate',
    percentage: 80,
    category: 'engineering',
    description: 'Prinsip desain berfokus pada pengguna, pemetaan empati, arsitektur informasi, psikologi warna, dan riset pengguna.',
    isStarred: true,
  },
  {
    id: 'sys_analysis',
    name: 'System Analysis',
    level: 'Intermediate',
    percentage: 76,
    category: 'engineering',
    description: 'Analisis kebutuhan sistem, pemodelan proses bisnis, use case diagram, dan estimasi beban kerja sistem informasi.',
    isStarred: true,
  },
  {
    id: 'db_design',
    name: 'Database Design',
    level: 'Intermediate',
    percentage: 78,
    category: 'engineering',
    description: 'Perancangan diagram ERD, mendefinisikan kunci (PK/FK), optimasi integritas referensial, dan manajemen konkurensi.',
  },
  {
    id: 'responsive_web',
    name: 'Responsive Web Design',
    level: 'Advanced',
    percentage: 88,
    category: 'engineering',
    description: 'Membangun desain fluid yang beradaptasi sempurna di berbagai resolusi layar, dari layar telepon genggam hingga layar ultra-lebar.',
  },
  {
    id: 'sdlc',
    name: 'SDLC',
    level: 'Intermediate',
    percentage: 75,
    category: 'engineering',
    description: 'Pemahaman siklus hidup perangkat lunak dari tahap analisis kebutuhan, perancangan, koding, pengujian, hingga rilis.',
  },
  {
    id: 'change_management',
    name: 'Change Management Fundamentals',
    level: 'Intermediate',
    percentage: 70,
    category: 'engineering',
    description: 'Dasar-dasar pengelolaan transisi proses bisnis agar implementasi teknologi baru diterima dengan baik oleh pengguna.',
  },
  {
    id: 'agile',
    name: 'Agile Collaboration',
    level: 'Intermediate',
    percentage: 76,
    category: 'engineering',
    description: 'Koordinasi tim yang fleksibel menggunakan Scrum/Kanban, standups rutin, dan adaptasi berkelanjutan terhadap kebutuhan proyek.',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'work_well',
    title: 'Work Well',
    description: 'Platform manajemen kolaborasi tim dan produktivitas mandiri. Memiliki arsitektur sinkronisasi waktu-nyata yang mulus sehingga mendistribusikan pembaruan tugas secara instan tanpa hambatan.',
    techStack: ['React.js', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Responsive Design'],
    category: 'Aplikasi Kolaborasi Produktivitas',
    features: [
      'Sinkronisasi Tugas secara Real-Time',
      'Desain Tata Letak Adaptif',
      'Arsitektur Multi-Tenancy Sederhana',
      'Papan Kerja Tim (Kanban)',
    ],
    businessValue: 'Meningkatkan transparansi beban kerja tim sebesar 40% dan mengeliminasi latensi koordinasi menggunakan push-notification bawaan.',
    mockupBg: 'bg-gradient-to-tr from-cyan-950 via-teal-900 to-emerald-950',
    externalUrl: 'https://openoffice-customer.vercel.app/',
  },
  {
    id: 'open_office',
    title: 'Open Office Admin Dashboard',
    description: 'Aplikasi dashboard administrasi eksekutif lengkap yang dirancang khusus untuk memonitor aliran data operasional, melacak kehadiran/aktivitas, serta menghasilkan analisis performa organisasi terstruktur.',
    techStack: ['React.js', 'TypeScript', 'Supabase', 'Analytics Dashboard', 'Management System'],
    category: 'Dashboard Internal Perusahaan',
    features: [
      'Visualisasi Data Statistik Kunci',
      'Manajemen Hak Akses Pengguna (RBAC)',
      'Ekspor Laporan Otomatis',
      'Audit Trail Pergerakan Basis Data',
    ],
    businessValue: 'Mempercepat pengambilan keputusan strategis dari data harian, memotong waktu penyusunan laporan operasional mingguan dari berjam-jam menjadi beberapa detik.',
    mockupBg: 'bg-gradient-to-tr from-slate-950 via-blue-950 to-indigo-950',
    externalUrl: 'https://openoffice-admin-psi.vercel.app/',
  },
  {
    id: 'its_threedi',
    title: 'Its.Threedi',
    description: 'Platform penemuan sosial-commerce modern di mana pengguna dapat mengeksplorasi katalog kurasi produk digital secara interaktif dengan antarmuka dinamis dan transaksi sosial yang terpadu.',
    techStack: ['React.js', 'JavaScript', 'Tailwind CSS', 'UI/UX Design', 'Social Commerce'],
    category: 'Inovasi E-Commerce Sosial',
    features: [
      'Antarmuka Kurasi Estetik',
      'Sistem Rekomendasi Dinamis Berdasarkan Minat',
      'Desain UX Berfokus pada Konversi Tinggi',
      'Navigasi Eksplorasi Fluid berbasis Kartu',
    ],
    businessValue: 'Menjembatani interaksi sosial dan keputusan belanja langsung untuk generasi muda, meningkatkan retensi perhatian pengguna (user session duration) di halaman katalog.',
    mockupBg: 'bg-gradient-to-tr from-neutral-950 via-zinc-900 to-stone-900',
    externalUrl: 'https://websiteitsthreedi.vercel.app/',
  },
  {
    id: 'agritech_figma',
    title: 'AgriTech Plan & Interactive Prototype',
    description: 'Rancangan komparatif bisnis plan inovatif AgriTech dan penciptaan prototipe maket interaktif berskala tinggi. Menyediakan blueprint sistem irigasi siram cerdas, pemonitoran cuaca waktu-nyata, pendataan aset pertanian berkelanjutan, dan kalkulator kalkulasi tani.',
    techStack: ['Figma Prototyping', 'UI/UX Design', 'AgriTech Business Strategy', 'Smart Irrigation Product Design'],
    category: 'Smart Agriculture Plan & UI/UX',
    features: [
      'Aliran Autentikasi Pengguna & OTP',
      'Skema Panel Manajemen Lahan & Siram',
      'Predator Grafis Pendapatan Tani',
      'Uji Coba Aliran Navigasi Prototipe Figma',
    ],
    businessValue: 'Menjembatani akses teknologi modern bagi petani lokal serta menawarkan presentasi bisnis plan visibel dengan visualisasi UX berkelas.',
    mockupBg: 'bg-gradient-to-tr from-yellow-950 via-amber-900 to-orange-950',
    externalUrl: 'https://www.figma.com/proto/Gud5vE2QZsb6ZAZL4ztj55/Agri-Tech?node-id=0-1&t=ALmS82oa7oo21U6I-1',
  },
  {
    id: 'wonosobo_gis',
    title: 'Wonosobo GIS (Kapita Selekta)',
    description: 'Website Sistem Informasi Geografis (GIS) wilayah Wonosobo jawa tengah yang saya kembangkan secara responsif untuk memetakan zona kawasan pendakian gunung (Sindoro, Kembang), elevasi puncak, koordinasi titik pos istirahat, dan penyajian data spasial interaktif.',
    techStack: ['HTML', 'CSS', 'JavaScript', 'Leaflet.js', 'GIS Mapping'],
    category: 'Geographic Information System',
    features: [
      'Pemetaan Rute Jalur Pendakian',
      'Layer Kontrol Interaktif (Basecamp, Puncak)',
      'Data Elevasi Spasial',
      'Informasi Zona Hutan & Aliran Air',
    ],
    businessValue: 'Mempermudah navigasi pendaki gunung secara mandiri dengan integrasi peta presisi tanpa bergantung koneksi server berat.',
    mockupBg: 'bg-gradient-to-tr from-emerald-950 via-green-900 to-teal-950',
    externalUrl: 'https://edivho-wonosobo-uts-kapita.vercel.app/',
  },
];

export const RECRUITER_REASONS: RecruiterReason[] = [
  {
    id: 'reason_1',
    iconName: 'Brain',
    title: 'Pola Pikir Pemecah Masalah yang Kuat',
    description: 'Menjembatani kesenjangan kompleksitas sistem dengan solusi komputasi yang logis dan efisien demi kemudahan pengguna.',
    extendedDetail: 'Fokus pada penyederhanaan arsitektur kompleks. Dalam setiap tantangan koding, saya selalu mencari akar masalah untuk menghasilkan solusi yang tidak hanya fungsional tetapi juga terukur dan mudah dirawat dalam jangka panjang.',
  },
  {
    id: 'reason_2',
    iconName: 'Users',
    title: 'Pengalaman Memimpin Organisasi Mahasiswa',
    description: 'Pernah memimpin sebagai Ketua Pelaksana ISO (ospek jurusan) di HMSI, dan sekarang menjabat sebagai Wakil Ketua HMSI di periode kedua.',
    extendedDetail: 'Sebagai mahasiswa Sistem Informasi di Universitas Bakrie, saya memiliki rekam jejak kepemimpinan aktif. Saya pernah memimpin sebagai Ketua Pelaksana ISO (ospek jurusan) yang merupakan salah satu program kerja Himpunan Mahasiswa Sistem Informasi (HMSI), dan saat ini saya dipercaya menjabat sebagai Wakil Ketua HMSI di periode kedua untuk memimpin koordinasi internal serta menyukseskan program kerja taktis himpunan.',
  },
  {
    id: 'reason_3',
    iconName: 'Code',
    title: 'Proyek Pengembangan Perangkat Lunak Praktis',
    description: 'Memiliki portfolio aplikasi nyata yang berjalan baik dengan database modern, bukan sekadar teori akademis.',
    extendedDetail: 'Portofolio saya mendemonstrasikan kapabilitas operasional konkret dengan stack andalan seperti React, TypeScript, dan SQL/Supabase, yang dirakit dengan standar kualitas industri dan best practices terkini.',
  },
  {
    id: 'reason_4',
    iconName: 'Workflow',
    title: 'Paham Penyelarasan Bisnis & Teknologi',
    description: 'Menganalisis sistem informasi dari perspektif penciptaan nilai komersial maupun kegunaan teknikalnya.',
    extendedDetail: 'Latar belakang Sistem Informasi membekali saya untuk menerjemahkan kebutuhan bisnis stakeholder menjadi spesifikasi fitur teknis secara mulus, menjaga keselarasan fungsionalitas dan ROI solusi digital.',
  },
  {
    id: 'reason_5',
    iconName: 'Rocket',
    title: 'Pembelajar Cepat & Pemain Tim Adaptif',
    description: 'Mampu mengasimilasi framework baru dalam hitungan hari dan berkolaborasi secara produktif lewat metodologi Agile.',
    extendedDetail: 'Dunia teknologi bergerak sangat dinamis. Saya memiliki kapabilitas adaptasi mandiri yang tinggi, siap menyongsong stack teknologi baru, dan merangkul feedback konstruktif guna mematangkan produk tim.',
  },
  {
    id: 'reason_6',
    iconName: 'Sparkles',
    title: 'Semangat Tinggi Membangun Produk Berdampak',
    description: 'Mendandani visual seindah kegunaannya demi menyajikan kepuasan digital yang sesungguhnya ke end-user.',
    extendedDetail: 'Bagi saya, baris kode hanyalah sarana; tujuan utamanya adalah memberdayakan pengguna melalui pengalaman interaksi digital yang menyenangkan, aksesibel, dan benar-benar menuntaskan problem riil mereka.',
  },
];
